version: '3'
services:
  database:
    image: postgres:16
    env_file:
      - ./.env.dev
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    env_file:
      - ./.env.dev
    expose:
      - 8000
    volumes:
      - ./backend:/backend
      - static_volume:/backend/djangostatic
      - media_volume:/backend/djangomedia
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
      - WDS_SOCKET_PORT=0
    expose:
      - 3000
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    depends_on:
      - backend
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
      - static_volume:/backend/djangostatic
      - media_volume:/backend/djangomedia
    ports:
      - 1337:80
volumes:
  postgres_data:
  static_volume:
  media_volume: