version: '3'
services:
  database:
    image: postgres:16
    environment:
        - POSTGRES_PASSWORD=postgrespassword
        - POSTGRES_USER=postgresuser
        - POSTGRES_DB=postgresdb
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    environment:
      - DJANGO_SECRET_KEY=django-insecure-npiw)m2=8#nazx+hssjg^kh%df^0j9ri6v!5la#4@gea@t+m&9
      - DJANGO_DEBUG=True
      - POSTGRES_NAME=postgresdb
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespassword
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/backend
    depends_on:
      - database
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /frontend/node_modules
      - ./frontend:/frontend
    depends_on:
      - backend