version: "3"
services:
  backend:
    image: "ethomazrosa/maverick_backend"
    mem_limit: 128m
    hostname: backend
    environment:
      - DJANGO_SECRET_KEY=$DJANGO_SECRET_KEY
      - DJANGO_DEBUG=$DJANGO_DEBUG
      - DJANGO_ALLOWED_HOSTS=$DJANGO_ALLOWED_HOSTS
      - DJANGO_CSRF_TRUSTED_ORIGINS=$DJANGO_CSRF_TRUSTED_ORIGINS
      - DJANGO_CORS_ALLOWED_ORIGINS=$DJANGO_CORS_ALLOWED_ORIGINS
      - DATABASE=$DATABASE
      - POSTGRES_NAME=$POSTGRES_NAME
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
      - POSTGRES_HOST=$POSTGRES_HOST
      - POSTGRES_PORT=$POSTGRES_PORT
  frontend:
    image: "ethomazrosa/maverick_frontend"
    mem_limit: 128m
    hostname: frontend
  nginx:
    image: "ethomazrosa/maverick_nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"
