# Generated by Django 5.0.1 on 2024-01-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="identification_number",
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="mobile_phone",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="municipal_registration",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="postal_code",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="state_registration",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="ncm_naladish",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="responsiblecompany",
            name="address_number",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="responsiblecompany",
            name="identification_number",
            field=models.PositiveBigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name="responsiblecompany",
            name="mobile_phone",
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name="responsiblecompany",
            name="municipal_registration",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="responsiblecompany",
            name="phone",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="responsiblecompany",
            name="postal_code",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="responsiblecompany",
            name="state_registration",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
