# Generated by Django 5.0.1 on 2024-01-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0002_alter_customer_address_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="profit_percentage",
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
