# Generated by Django 5.0.1 on 2024-01-16 13:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("registrations", "0003_alter_product_profit_percentage"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact", models.CharField(blank=True, max_length=250, null=True)),
                ("seller", models.CharField(max_length=250)),
                ("date", models.DateField()),
                ("expiration_date", models.DateField()),
                ("service_description", models.CharField(max_length=1000)),
                ("payment_method", models.CharField(max_length=1000)),
                ("warranty", models.CharField(max_length=1000)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Rascunho"),
                            ("PENDING", "Pendente"),
                            ("SENT", "Enviado"),
                            ("ACCEPTED", "Aceito"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="registrations.customer",
                    ),
                ),
                (
                    "service_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="service_locations",
                        to="registrations.customer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuoteProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="registrations.product",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.quote"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuoteService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "quote",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="sales.quote"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="registrations.service",
                    ),
                ),
            ],
        ),
    ]
