# Generated by Django 5.0.1 on 2024-01-16 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quote",
            options={"verbose_name": "Orçamento"},
        ),
        migrations.AlterModelOptions(
            name="quoteproduct",
            options={"verbose_name": "Orçamentos/Produto"},
        ),
        migrations.AlterModelOptions(
            name="quoteservice",
            options={"verbose_name": "Orçamentos/Serviço"},
        ),
        migrations.AlterField(
            model_name="quoteproduct",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="sales.quote",
            ),
        ),
    ]
