# Generated by Django 5.0.1 on 2024-01-16 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_alter_quote_options_alter_quoteproduct_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quoteservice",
            name="quote",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="sales.quote",
            ),
        ),
    ]
