# Generated by Django 5.0.1 on 2024-01-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_alter_quoteservice_quote"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="deadline",
            field=models.CharField(default="10 dias.", max_length=1000),
            preserve_default=False,
        ),
    ]
