# Generated by Django 5.0.1 on 2024-01-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("registrations", "0004_alter_customer_options_alter_product_options_and_more"),
        ("sales", "0004_quote_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoteproduct",
            name="number",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quoteservice",
            name="number",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="quoteproduct",
            constraint=models.UniqueConstraint(
                fields=("quote", "number"), name="product_number"
            ),
        ),
        migrations.AddConstraint(
            model_name="quoteservice",
            constraint=models.UniqueConstraint(
                fields=("quote", "number"), name="service_number"
            ),
        ),
    ]
