# Generated by Django 5.0.1 on 2024-01-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="identification_number",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
