name: Deploy Maverick ERP

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t ethomazrosa/maverick_backend ./backend
      - run: docker build -t ethomazrosa/maverick_frontend ./frontend
      - run: docker build -t ethomazrosa/maverick_nginx ./nginx
      
      - run: docker push ethomazrosa/maverick_backend
      - run: docker push ethomazrosa/maverick_frontend
      - run: docker push ethomazrosa/maverick_nginx

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: maverick-erp
          environment_name: Maverick-erp-env
          existing_bucket_name: elasticbeanstalk-sa-east-1-590183750641
          region: sa-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip